In [8]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression as lr

In [9]:
dataframe = pd.read_csv('advertising_and_sales_clean.csv')
print(len(dataframe))

dataframe_clean = dataframe[dataframe['sales'] > 0]
print(len(dataframe_clean))

display(dataframe.head(20))

4546
4546

          tv     radio  social_media influencer      sales
0    16000.0   6566.23       2907.98       Mega   54732.76
1    13000.0   9237.76       2409.57       Mega   46677.90
2    41000.0  15886.45       2913.41       Mega  150177.83
3    83000.0  30020.03       6922.30       Mega  298246.34
4    15000.0   8437.41       1406.00      Micro   56594.18
5    29000.0   9614.38       1027.16       Mega  105889.15
6    55000.0  24893.81       4273.60      Micro  198679.82
7    31000.0  17355.04       2289.85       Nano  108733.93
8    76000.0  24648.90       7130.12      Macro  270189.40
9    13000.0    431.13       2229.42       Mega   48280.58
10   62000.0  24345.19       5151.48       Nano  224961.02
11   42000.0  15807.34       3194.92       Mega  145543.99
12   64000.0  20240.42       3921.15      Micro  229632.38
13   34000.0    226.33       2372.71       Nano  121336.42
14   36000.0   3900.20         60.40       Nano  123526.11
15   60000.0  22353.72        940.80       Mega  212764.40
16   25000.0   9905.84       1853.22      Micro   89819.92
17  100000.0  36116.09       3674.30      Macro  353804.64
18   92000.0  40736.99       4636.56       Nano  329350.54
19   46000.0  12695.09       3884.58      Macro  162191.33